// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processjob.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "processjob.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ProcessJob_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProcessJob_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ProcessJob_Action_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ProcessJob_Result_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_processjob_2eproto() {
  protobuf_AddDesc_processjob_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "processjob.proto");
  GOOGLE_CHECK(file != NULL);
  ProcessJob_descriptor_ = file->message_type(0);
  static const int ProcessJob_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, quid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, content_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, partition_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, jobaction_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, jobresult_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, runtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, returncode_),
  };
  ProcessJob_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ProcessJob_descriptor_,
      ProcessJob::default_instance_,
      ProcessJob_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessJob, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ProcessJob));
  ProcessJob_Action_descriptor_ = ProcessJob_descriptor_->enum_type(0);
  ProcessJob_Result_descriptor_ = ProcessJob_descriptor_->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_processjob_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ProcessJob_descriptor_, &ProcessJob::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_processjob_2eproto() {
  delete ProcessJob::default_instance_;
  delete ProcessJob_reflection_;
}

void protobuf_AddDesc_processjob_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020processjob.proto\"\252\002\n\nProcessJob\022\014\n\004nam"
    "e\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\014\n\004quid\030\003 \001(\t\022\017\n\007con"
    "tent\030\004 \001(\014\022\021\n\tpartition\030\005 \002(\005\022%\n\tjobacti"
    "on\030\006 \002(\0162\022.ProcessJob.Action\022%\n\tjobresul"
    "t\030\007 \002(\0162\022.ProcessJob.Result\022\017\n\007runtime\030\010"
    " \002(\005\022\025\n\nreturncode\030\t \002(\005:\0010\"+\n\006Action\022\013\n"
    "\007SOLICIT\020\000\022\010\n\004IDLE\020\001\022\n\n\006ACCEPT\020\002\"-\n\006Resu"
    "lt\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020\001\022\014\n\010HARDFAIL\020\002", 319);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "processjob.proto", &protobuf_RegisterTypes);
  ProcessJob::default_instance_ = new ProcessJob();
  ProcessJob::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_processjob_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_processjob_2eproto {
  StaticDescriptorInitializer_processjob_2eproto() {
    protobuf_AddDesc_processjob_2eproto();
  }
} static_descriptor_initializer_processjob_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ProcessJob_Action_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProcessJob_Action_descriptor_;
}
bool ProcessJob_Action_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ProcessJob_Action ProcessJob::SOLICIT;
const ProcessJob_Action ProcessJob::IDLE;
const ProcessJob_Action ProcessJob::ACCEPT;
const ProcessJob_Action ProcessJob::Action_MIN;
const ProcessJob_Action ProcessJob::Action_MAX;
const int ProcessJob::Action_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* ProcessJob_Result_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProcessJob_Result_descriptor_;
}
bool ProcessJob_Result_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ProcessJob_Result ProcessJob::SUCCESS;
const ProcessJob_Result ProcessJob::FAIL;
const ProcessJob_Result ProcessJob::HARDFAIL;
const ProcessJob_Result ProcessJob::Result_MIN;
const ProcessJob_Result ProcessJob::Result_MAX;
const int ProcessJob::Result_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ProcessJob::kNameFieldNumber;
const int ProcessJob::kIdFieldNumber;
const int ProcessJob::kQuidFieldNumber;
const int ProcessJob::kContentFieldNumber;
const int ProcessJob::kPartitionFieldNumber;
const int ProcessJob::kJobactionFieldNumber;
const int ProcessJob::kJobresultFieldNumber;
const int ProcessJob::kRuntimeFieldNumber;
const int ProcessJob::kReturncodeFieldNumber;
#endif  // !_MSC_VER

ProcessJob::ProcessJob()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProcessJob)
}

void ProcessJob::InitAsDefaultInstance() {
}

ProcessJob::ProcessJob(const ProcessJob& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ProcessJob)
}

void ProcessJob::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  quid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  partition_ = 0;
  jobaction_ = 0;
  jobresult_ = 0;
  runtime_ = 0;
  returncode_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ProcessJob::~ProcessJob() {
  // @@protoc_insertion_point(destructor:ProcessJob)
  SharedDtor();
}

void ProcessJob::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (quid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete quid_;
  }
  if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete content_;
  }
  if (this != default_instance_) {
  }
}

void ProcessJob::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProcessJob::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProcessJob_descriptor_;
}

const ProcessJob& ProcessJob::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_processjob_2eproto();
  return *default_instance_;
}

ProcessJob* ProcessJob::default_instance_ = NULL;

ProcessJob* ProcessJob::New() const {
  return new ProcessJob;
}

void ProcessJob::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ProcessJob*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(id_, partition_);
    ZR_(jobaction_, runtime_);
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    if (has_quid()) {
      if (quid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        quid_->clear();
      }
    }
    if (has_content()) {
      if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        content_->clear();
      }
    }
  }
  returncode_ = 0;

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ProcessJob::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProcessJob)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_id;
        break;
      }

      // required int32 id = 2;
      case 2: {
        if (tag == 16) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_quid;
        break;
      }

      // optional string quid = 3;
      case 3: {
        if (tag == 26) {
         parse_quid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_quid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->quid().data(), this->quid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "quid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_content;
        break;
      }

      // optional bytes content = 4;
      case 4: {
        if (tag == 34) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_content()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_partition;
        break;
      }

      // required int32 partition = 5;
      case 5: {
        if (tag == 40) {
         parse_partition:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &partition_)));
          set_has_partition();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_jobaction;
        break;
      }

      // required .ProcessJob.Action jobaction = 6;
      case 6: {
        if (tag == 48) {
         parse_jobaction:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ProcessJob_Action_IsValid(value)) {
            set_jobaction(static_cast< ::ProcessJob_Action >(value));
          } else {
            mutable_unknown_fields()->AddVarint(6, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_jobresult;
        break;
      }

      // required .ProcessJob.Result jobresult = 7;
      case 7: {
        if (tag == 56) {
         parse_jobresult:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ProcessJob_Result_IsValid(value)) {
            set_jobresult(static_cast< ::ProcessJob_Result >(value));
          } else {
            mutable_unknown_fields()->AddVarint(7, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_runtime;
        break;
      }

      // required int32 runtime = 8;
      case 8: {
        if (tag == 64) {
         parse_runtime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &runtime_)));
          set_has_runtime();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_returncode;
        break;
      }

      // required int32 returncode = 9 [default = 0];
      case 9: {
        if (tag == 72) {
         parse_returncode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));
          set_has_returncode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProcessJob)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProcessJob)
  return false;
#undef DO_
}

void ProcessJob::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProcessJob)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required int32 id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // optional string quid = 3;
  if (has_quid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->quid().data(), this->quid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "quid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->quid(), output);
  }

  // optional bytes content = 4;
  if (has_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->content(), output);
  }

  // required int32 partition = 5;
  if (has_partition()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->partition(), output);
  }

  // required .ProcessJob.Action jobaction = 6;
  if (has_jobaction()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->jobaction(), output);
  }

  // required .ProcessJob.Result jobresult = 7;
  if (has_jobresult()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      7, this->jobresult(), output);
  }

  // required int32 runtime = 8;
  if (has_runtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->runtime(), output);
  }

  // required int32 returncode = 9 [default = 0];
  if (has_returncode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->returncode(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProcessJob)
}

::google::protobuf::uint8* ProcessJob::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProcessJob)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required int32 id = 2;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // optional string quid = 3;
  if (has_quid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->quid().data(), this->quid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "quid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->quid(), target);
  }

  // optional bytes content = 4;
  if (has_content()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->content(), target);
  }

  // required int32 partition = 5;
  if (has_partition()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->partition(), target);
  }

  // required .ProcessJob.Action jobaction = 6;
  if (has_jobaction()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->jobaction(), target);
  }

  // required .ProcessJob.Result jobresult = 7;
  if (has_jobresult()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      7, this->jobresult(), target);
  }

  // required int32 runtime = 8;
  if (has_runtime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->runtime(), target);
  }

  // required int32 returncode = 9 [default = 0];
  if (has_returncode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->returncode(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProcessJob)
  return target;
}

int ProcessJob::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required int32 id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional string quid = 3;
    if (has_quid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->quid());
    }

    // optional bytes content = 4;
    if (has_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->content());
    }

    // required int32 partition = 5;
    if (has_partition()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->partition());
    }

    // required .ProcessJob.Action jobaction = 6;
    if (has_jobaction()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->jobaction());
    }

    // required .ProcessJob.Result jobresult = 7;
    if (has_jobresult()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->jobresult());
    }

    // required int32 runtime = 8;
    if (has_runtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->runtime());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required int32 returncode = 9 [default = 0];
    if (has_returncode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->returncode());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProcessJob::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ProcessJob* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ProcessJob*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ProcessJob::MergeFrom(const ProcessJob& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_quid()) {
      set_quid(from.quid());
    }
    if (from.has_content()) {
      set_content(from.content());
    }
    if (from.has_partition()) {
      set_partition(from.partition());
    }
    if (from.has_jobaction()) {
      set_jobaction(from.jobaction());
    }
    if (from.has_jobresult()) {
      set_jobresult(from.jobresult());
    }
    if (from.has_runtime()) {
      set_runtime(from.runtime());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_returncode()) {
      set_returncode(from.returncode());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ProcessJob::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProcessJob::CopyFrom(const ProcessJob& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessJob::IsInitialized() const {
  if ((_has_bits_[0] & 0x000001f3) != 0x000001f3) return false;

  return true;
}

void ProcessJob::Swap(ProcessJob* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(id_, other->id_);
    std::swap(quid_, other->quid_);
    std::swap(content_, other->content_);
    std::swap(partition_, other->partition_);
    std::swap(jobaction_, other->jobaction_);
    std::swap(jobresult_, other->jobresult_);
    std::swap(runtime_, other->runtime_);
    std::swap(returncode_, other->returncode_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ProcessJob::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProcessJob_descriptor_;
  metadata.reflection = ProcessJob_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
