// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processjob.proto

#ifndef PROTOBUF_processjob_2eproto__INCLUDED
#define PROTOBUF_processjob_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_processjob_2eproto();
void protobuf_AssignDesc_processjob_2eproto();
void protobuf_ShutdownFile_processjob_2eproto();

class ProcessJob;

// ===================================================================

class ProcessJob : public ::google::protobuf::Message {
 public:
  ProcessJob();
  virtual ~ProcessJob();

  ProcessJob(const ProcessJob& from);

  inline ProcessJob& operator=(const ProcessJob& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProcessJob& default_instance();

  void Swap(ProcessJob* other);

  // implements Message ----------------------------------------------

  ProcessJob* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProcessJob& from);
  void MergeFrom(const ProcessJob& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string quid = 3;
  inline bool has_quid() const;
  inline void clear_quid();
  static const int kQuidFieldNumber = 3;
  inline const ::std::string& quid() const;
  inline void set_quid(const ::std::string& value);
  inline void set_quid(const char* value);
  inline void set_quid(const char* value, size_t size);
  inline ::std::string* mutable_quid();
  inline ::std::string* release_quid();
  inline void set_allocated_quid(::std::string* quid);

  // optional bytes content = 4;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 4;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const void* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // required int32 partition = 5;
  inline bool has_partition() const;
  inline void clear_partition();
  static const int kPartitionFieldNumber = 5;
  inline ::google::protobuf::int32 partition() const;
  inline void set_partition(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ProcessJob)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_quid();
  inline void clear_has_quid();
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_partition();
  inline void clear_has_partition();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* quid_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 partition_;
  ::std::string* content_;
  friend void  protobuf_AddDesc_processjob_2eproto();
  friend void protobuf_AssignDesc_processjob_2eproto();
  friend void protobuf_ShutdownFile_processjob_2eproto();

  void InitAsDefaultInstance();
  static ProcessJob* default_instance_;
};
// ===================================================================


// ===================================================================

// ProcessJob

// required string name = 1;
inline bool ProcessJob::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProcessJob::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProcessJob::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProcessJob::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ProcessJob::name() const {
  // @@protoc_insertion_point(field_get:ProcessJob.name)
  return *name_;
}
inline void ProcessJob::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:ProcessJob.name)
}
inline void ProcessJob::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:ProcessJob.name)
}
inline void ProcessJob::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ProcessJob.name)
}
inline ::std::string* ProcessJob::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ProcessJob.name)
  return name_;
}
inline ::std::string* ProcessJob::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ProcessJob::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ProcessJob.name)
}

// required int32 id = 2;
inline bool ProcessJob::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProcessJob::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProcessJob::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProcessJob::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ProcessJob::id() const {
  // @@protoc_insertion_point(field_get:ProcessJob.id)
  return id_;
}
inline void ProcessJob::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ProcessJob.id)
}

// optional string quid = 3;
inline bool ProcessJob::has_quid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProcessJob::set_has_quid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProcessJob::clear_has_quid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProcessJob::clear_quid() {
  if (quid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quid_->clear();
  }
  clear_has_quid();
}
inline const ::std::string& ProcessJob::quid() const {
  // @@protoc_insertion_point(field_get:ProcessJob.quid)
  return *quid_;
}
inline void ProcessJob::set_quid(const ::std::string& value) {
  set_has_quid();
  if (quid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quid_ = new ::std::string;
  }
  quid_->assign(value);
  // @@protoc_insertion_point(field_set:ProcessJob.quid)
}
inline void ProcessJob::set_quid(const char* value) {
  set_has_quid();
  if (quid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quid_ = new ::std::string;
  }
  quid_->assign(value);
  // @@protoc_insertion_point(field_set_char:ProcessJob.quid)
}
inline void ProcessJob::set_quid(const char* value, size_t size) {
  set_has_quid();
  if (quid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quid_ = new ::std::string;
  }
  quid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ProcessJob.quid)
}
inline ::std::string* ProcessJob::mutable_quid() {
  set_has_quid();
  if (quid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ProcessJob.quid)
  return quid_;
}
inline ::std::string* ProcessJob::release_quid() {
  clear_has_quid();
  if (quid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = quid_;
    quid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ProcessJob::set_allocated_quid(::std::string* quid) {
  if (quid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete quid_;
  }
  if (quid) {
    set_has_quid();
    quid_ = quid;
  } else {
    clear_has_quid();
    quid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ProcessJob.quid)
}

// optional bytes content = 4;
inline bool ProcessJob::has_content() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProcessJob::set_has_content() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProcessJob::clear_has_content() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProcessJob::clear_content() {
  if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& ProcessJob::content() const {
  // @@protoc_insertion_point(field_get:ProcessJob.content)
  return *content_;
}
inline void ProcessJob::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  content_->assign(value);
  // @@protoc_insertion_point(field_set:ProcessJob.content)
}
inline void ProcessJob::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  content_->assign(value);
  // @@protoc_insertion_point(field_set_char:ProcessJob.content)
}
inline void ProcessJob::set_content(const void* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ProcessJob.content)
}
inline ::std::string* ProcessJob::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ProcessJob.content)
  return content_;
}
inline ::std::string* ProcessJob::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ProcessJob::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ProcessJob.content)
}

// required int32 partition = 5;
inline bool ProcessJob::has_partition() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProcessJob::set_has_partition() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProcessJob::clear_has_partition() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProcessJob::clear_partition() {
  partition_ = 0;
  clear_has_partition();
}
inline ::google::protobuf::int32 ProcessJob::partition() const {
  // @@protoc_insertion_point(field_get:ProcessJob.partition)
  return partition_;
}
inline void ProcessJob::set_partition(::google::protobuf::int32 value) {
  set_has_partition();
  partition_ = value;
  // @@protoc_insertion_point(field_set:ProcessJob.partition)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_processjob_2eproto__INCLUDED
