// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scrapedata.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "scrapedata.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ScrapeData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ScrapeData_reflection_ = NULL;
const ::google::protobuf::Descriptor* ScrapeData_Data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ScrapeData_Data_reflection_ = NULL;
const ::google::protobuf::Descriptor* ScrapeData_MetaEntry_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ScrapeData_MetaEntry_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ScrapeData_DataType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_scrapedata_2eproto() {
  protobuf_AddDesc_scrapedata_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "scrapedata.proto");
  GOOGLE_CHECK(file != NULL);
  ScrapeData_descriptor_ = file->message_type(0);
  static const int ScrapeData_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, quid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, zone_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, content_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, meta_),
  };
  ScrapeData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ScrapeData_descriptor_,
      ScrapeData::default_instance_,
      ScrapeData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ScrapeData));
  ScrapeData_Data_descriptor_ = ScrapeData_descriptor_->nested_type(0);
  static const int ScrapeData_Data_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_Data, payload_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_Data, size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_Data, extension_),
  };
  ScrapeData_Data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ScrapeData_Data_descriptor_,
      ScrapeData_Data::default_instance_,
      ScrapeData_Data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_Data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_Data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ScrapeData_Data));
  ScrapeData_MetaEntry_descriptor_ = ScrapeData_descriptor_->nested_type(1);
  static const int ScrapeData_MetaEntry_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_MetaEntry, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_MetaEntry, value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_MetaEntry, meta_),
  };
  ScrapeData_MetaEntry_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ScrapeData_MetaEntry_descriptor_,
      ScrapeData_MetaEntry::default_instance_,
      ScrapeData_MetaEntry_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_MetaEntry, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScrapeData_MetaEntry, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ScrapeData_MetaEntry));
  ScrapeData_DataType_descriptor_ = ScrapeData_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_scrapedata_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ScrapeData_descriptor_, &ScrapeData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ScrapeData_Data_descriptor_, &ScrapeData_Data::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ScrapeData_MetaEntry_descriptor_, &ScrapeData_MetaEntry::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_scrapedata_2eproto() {
  delete ScrapeData::default_instance_;
  delete ScrapeData_reflection_;
  delete ScrapeData_Data::default_instance_;
  delete ScrapeData_Data_reflection_;
  delete ScrapeData_MetaEntry::default_instance_;
  delete ScrapeData_MetaEntry_reflection_;
}

void protobuf_AddDesc_scrapedata_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020scrapedata.proto\"\366\002\n\nScrapeData\022\014\n\004nam"
    "e\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\014\n\004quid\030\003 \001(\t\022\014\n\004zon"
    "e\030\004 \001(\t\022)\n\004type\030\005 \002(\0162\024.ScrapeData.DataT"
    "ype:\005PLAIN\022!\n\007content\030\006 \002(\0132\020.ScrapeData"
    ".Data\022#\n\004meta\030\007 \003(\0132\025.ScrapeData.MetaEnt"
    "ry\0328\n\004Data\022\017\n\007payload\030\001 \002(\014\022\014\n\004size\030\002 \001("
    "\004\022\021\n\textension\030\003 \001(\t\032L\n\tMetaEntry\022\013\n\003key"
    "\030\001 \002(\t\022\r\n\005value\030\002 \001(\014\022#\n\004meta\030\003 \003(\0132\025.Sc"
    "rapeData.MetaEntry\"7\n\010DataType\022\t\n\005PLAIN\020"
    "\000\022\010\n\004FILE\020\001\022\n\n\006BINARY\020\002\022\n\n\006STREAM\020\003", 395);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "scrapedata.proto", &protobuf_RegisterTypes);
  ScrapeData::default_instance_ = new ScrapeData();
  ScrapeData_Data::default_instance_ = new ScrapeData_Data();
  ScrapeData_MetaEntry::default_instance_ = new ScrapeData_MetaEntry();
  ScrapeData::default_instance_->InitAsDefaultInstance();
  ScrapeData_Data::default_instance_->InitAsDefaultInstance();
  ScrapeData_MetaEntry::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_scrapedata_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_scrapedata_2eproto {
  StaticDescriptorInitializer_scrapedata_2eproto() {
    protobuf_AddDesc_scrapedata_2eproto();
  }
} static_descriptor_initializer_scrapedata_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ScrapeData_DataType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ScrapeData_DataType_descriptor_;
}
bool ScrapeData_DataType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ScrapeData_DataType ScrapeData::PLAIN;
const ScrapeData_DataType ScrapeData::FILE;
const ScrapeData_DataType ScrapeData::BINARY;
const ScrapeData_DataType ScrapeData::STREAM;
const ScrapeData_DataType ScrapeData::DataType_MIN;
const ScrapeData_DataType ScrapeData::DataType_MAX;
const int ScrapeData::DataType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ScrapeData_Data::kPayloadFieldNumber;
const int ScrapeData_Data::kSizeFieldNumber;
const int ScrapeData_Data::kExtensionFieldNumber;
#endif  // !_MSC_VER

ScrapeData_Data::ScrapeData_Data()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ScrapeData.Data)
}

void ScrapeData_Data::InitAsDefaultInstance() {
}

ScrapeData_Data::ScrapeData_Data(const ScrapeData_Data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ScrapeData.Data)
}

void ScrapeData_Data::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  size_ = GOOGLE_ULONGLONG(0);
  extension_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ScrapeData_Data::~ScrapeData_Data() {
  // @@protoc_insertion_point(destructor:ScrapeData.Data)
  SharedDtor();
}

void ScrapeData_Data::SharedDtor() {
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete payload_;
  }
  if (extension_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extension_;
  }
  if (this != default_instance_) {
  }
}

void ScrapeData_Data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ScrapeData_Data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ScrapeData_Data_descriptor_;
}

const ScrapeData_Data& ScrapeData_Data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_scrapedata_2eproto();
  return *default_instance_;
}

ScrapeData_Data* ScrapeData_Data::default_instance_ = NULL;

ScrapeData_Data* ScrapeData_Data::New() const {
  return new ScrapeData_Data;
}

void ScrapeData_Data::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_payload()) {
      if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        payload_->clear();
      }
    }
    size_ = GOOGLE_ULONGLONG(0);
    if (has_extension()) {
      if (extension_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        extension_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ScrapeData_Data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ScrapeData.Data)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes payload = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_size;
        break;
      }

      // optional uint64 size = 2;
      case 2: {
        if (tag == 16) {
         parse_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &size_)));
          set_has_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_extension;
        break;
      }

      // optional string extension = 3;
      case 3: {
        if (tag == 26) {
         parse_extension:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_extension()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->extension().data(), this->extension().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "extension");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ScrapeData.Data)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ScrapeData.Data)
  return false;
#undef DO_
}

void ScrapeData_Data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ScrapeData.Data)
  // required bytes payload = 1;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->payload(), output);
  }

  // optional uint64 size = 2;
  if (has_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->size(), output);
  }

  // optional string extension = 3;
  if (has_extension()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->extension().data(), this->extension().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "extension");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->extension(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ScrapeData.Data)
}

::google::protobuf::uint8* ScrapeData_Data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ScrapeData.Data)
  // required bytes payload = 1;
  if (has_payload()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->payload(), target);
  }

  // optional uint64 size = 2;
  if (has_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->size(), target);
  }

  // optional string extension = 3;
  if (has_extension()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->extension().data(), this->extension().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "extension");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->extension(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ScrapeData.Data)
  return target;
}

int ScrapeData_Data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes payload = 1;
    if (has_payload()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->payload());
    }

    // optional uint64 size = 2;
    if (has_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->size());
    }

    // optional string extension = 3;
    if (has_extension()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->extension());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ScrapeData_Data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ScrapeData_Data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ScrapeData_Data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ScrapeData_Data::MergeFrom(const ScrapeData_Data& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_payload()) {
      set_payload(from.payload());
    }
    if (from.has_size()) {
      set_size(from.size());
    }
    if (from.has_extension()) {
      set_extension(from.extension());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ScrapeData_Data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScrapeData_Data::CopyFrom(const ScrapeData_Data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScrapeData_Data::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ScrapeData_Data::Swap(ScrapeData_Data* other) {
  if (other != this) {
    std::swap(payload_, other->payload_);
    std::swap(size_, other->size_);
    std::swap(extension_, other->extension_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ScrapeData_Data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ScrapeData_Data_descriptor_;
  metadata.reflection = ScrapeData_Data_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ScrapeData_MetaEntry::kKeyFieldNumber;
const int ScrapeData_MetaEntry::kValueFieldNumber;
const int ScrapeData_MetaEntry::kMetaFieldNumber;
#endif  // !_MSC_VER

ScrapeData_MetaEntry::ScrapeData_MetaEntry()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ScrapeData.MetaEntry)
}

void ScrapeData_MetaEntry::InitAsDefaultInstance() {
}

ScrapeData_MetaEntry::ScrapeData_MetaEntry(const ScrapeData_MetaEntry& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ScrapeData.MetaEntry)
}

void ScrapeData_MetaEntry::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ScrapeData_MetaEntry::~ScrapeData_MetaEntry() {
  // @@protoc_insertion_point(destructor:ScrapeData.MetaEntry)
  SharedDtor();
}

void ScrapeData_MetaEntry::SharedDtor() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void ScrapeData_MetaEntry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ScrapeData_MetaEntry::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ScrapeData_MetaEntry_descriptor_;
}

const ScrapeData_MetaEntry& ScrapeData_MetaEntry::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_scrapedata_2eproto();
  return *default_instance_;
}

ScrapeData_MetaEntry* ScrapeData_MetaEntry::default_instance_ = NULL;

ScrapeData_MetaEntry* ScrapeData_MetaEntry::New() const {
  return new ScrapeData_MetaEntry;
}

void ScrapeData_MetaEntry::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        key_->clear();
      }
    }
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        value_->clear();
      }
    }
  }
  meta_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ScrapeData_MetaEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ScrapeData.MetaEntry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "key");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // optional bytes value = 2;
      case 2: {
        if (tag == 18) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_meta;
        break;
      }

      // repeated .ScrapeData.MetaEntry meta = 3;
      case 3: {
        if (tag == 26) {
         parse_meta:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_meta()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_meta;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ScrapeData.MetaEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ScrapeData.MetaEntry)
  return false;
#undef DO_
}

void ScrapeData_MetaEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ScrapeData.MetaEntry)
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // optional bytes value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->value(), output);
  }

  // repeated .ScrapeData.MetaEntry meta = 3;
  for (int i = 0; i < this->meta_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->meta(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ScrapeData.MetaEntry)
}

::google::protobuf::uint8* ScrapeData_MetaEntry::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ScrapeData.MetaEntry)
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // optional bytes value = 2;
  if (has_value()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->value(), target);
  }

  // repeated .ScrapeData.MetaEntry meta = 3;
  for (int i = 0; i < this->meta_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->meta(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ScrapeData.MetaEntry)
  return target;
}

int ScrapeData_MetaEntry::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }

    // optional bytes value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->value());
    }

  }
  // repeated .ScrapeData.MetaEntry meta = 3;
  total_size += 1 * this->meta_size();
  for (int i = 0; i < this->meta_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->meta(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ScrapeData_MetaEntry::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ScrapeData_MetaEntry* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ScrapeData_MetaEntry*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ScrapeData_MetaEntry::MergeFrom(const ScrapeData_MetaEntry& from) {
  GOOGLE_CHECK_NE(&from, this);
  meta_.MergeFrom(from.meta_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ScrapeData_MetaEntry::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScrapeData_MetaEntry::CopyFrom(const ScrapeData_MetaEntry& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScrapeData_MetaEntry::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->meta())) return false;
  return true;
}

void ScrapeData_MetaEntry::Swap(ScrapeData_MetaEntry* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(value_, other->value_);
    meta_.Swap(&other->meta_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ScrapeData_MetaEntry::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ScrapeData_MetaEntry_descriptor_;
  metadata.reflection = ScrapeData_MetaEntry_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ScrapeData::kNameFieldNumber;
const int ScrapeData::kIdFieldNumber;
const int ScrapeData::kQuidFieldNumber;
const int ScrapeData::kZoneFieldNumber;
const int ScrapeData::kTypeFieldNumber;
const int ScrapeData::kContentFieldNumber;
const int ScrapeData::kMetaFieldNumber;
#endif  // !_MSC_VER

ScrapeData::ScrapeData()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ScrapeData)
}

void ScrapeData::InitAsDefaultInstance() {
  content_ = const_cast< ::ScrapeData_Data*>(&::ScrapeData_Data::default_instance());
}

ScrapeData::ScrapeData(const ScrapeData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ScrapeData)
}

void ScrapeData::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  quid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  zone_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
  content_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ScrapeData::~ScrapeData() {
  // @@protoc_insertion_point(destructor:ScrapeData)
  SharedDtor();
}

void ScrapeData::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (quid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete quid_;
  }
  if (zone_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete zone_;
  }
  if (this != default_instance_) {
    delete content_;
  }
}

void ScrapeData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ScrapeData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ScrapeData_descriptor_;
}

const ScrapeData& ScrapeData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_scrapedata_2eproto();
  return *default_instance_;
}

ScrapeData* ScrapeData::default_instance_ = NULL;

ScrapeData* ScrapeData::New() const {
  return new ScrapeData;
}

void ScrapeData::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ScrapeData*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 63) {
    ZR_(id_, type_);
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    if (has_quid()) {
      if (quid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        quid_->clear();
      }
    }
    if (has_zone()) {
      if (zone_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        zone_->clear();
      }
    }
    if (has_content()) {
      if (content_ != NULL) content_->::ScrapeData_Data::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  meta_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ScrapeData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ScrapeData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_id;
        break;
      }

      // required int32 id = 2;
      case 2: {
        if (tag == 16) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_quid;
        break;
      }

      // optional string quid = 3;
      case 3: {
        if (tag == 26) {
         parse_quid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_quid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->quid().data(), this->quid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "quid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_zone;
        break;
      }

      // optional string zone = 4;
      case 4: {
        if (tag == 34) {
         parse_zone:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_zone()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->zone().data(), this->zone().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "zone");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_type;
        break;
      }

      // required .ScrapeData.DataType type = 5 [default = PLAIN];
      case 5: {
        if (tag == 40) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ScrapeData_DataType_IsValid(value)) {
            set_type(static_cast< ::ScrapeData_DataType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_content;
        break;
      }

      // required .ScrapeData.Data content = 6;
      case 6: {
        if (tag == 50) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_content()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_meta;
        break;
      }

      // repeated .ScrapeData.MetaEntry meta = 7;
      case 7: {
        if (tag == 58) {
         parse_meta:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_meta()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_meta;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ScrapeData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ScrapeData)
  return false;
#undef DO_
}

void ScrapeData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ScrapeData)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required int32 id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // optional string quid = 3;
  if (has_quid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->quid().data(), this->quid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "quid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->quid(), output);
  }

  // optional string zone = 4;
  if (has_zone()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->zone().data(), this->zone().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "zone");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->zone(), output);
  }

  // required .ScrapeData.DataType type = 5 [default = PLAIN];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->type(), output);
  }

  // required .ScrapeData.Data content = 6;
  if (has_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->content(), output);
  }

  // repeated .ScrapeData.MetaEntry meta = 7;
  for (int i = 0; i < this->meta_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->meta(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ScrapeData)
}

::google::protobuf::uint8* ScrapeData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ScrapeData)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required int32 id = 2;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // optional string quid = 3;
  if (has_quid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->quid().data(), this->quid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "quid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->quid(), target);
  }

  // optional string zone = 4;
  if (has_zone()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->zone().data(), this->zone().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "zone");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->zone(), target);
  }

  // required .ScrapeData.DataType type = 5 [default = PLAIN];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->type(), target);
  }

  // required .ScrapeData.Data content = 6;
  if (has_content()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->content(), target);
  }

  // repeated .ScrapeData.MetaEntry meta = 7;
  for (int i = 0; i < this->meta_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->meta(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ScrapeData)
  return target;
}

int ScrapeData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required int32 id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional string quid = 3;
    if (has_quid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->quid());
    }

    // optional string zone = 4;
    if (has_zone()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->zone());
    }

    // required .ScrapeData.DataType type = 5 [default = PLAIN];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // required .ScrapeData.Data content = 6;
    if (has_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->content());
    }

  }
  // repeated .ScrapeData.MetaEntry meta = 7;
  total_size += 1 * this->meta_size();
  for (int i = 0; i < this->meta_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->meta(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ScrapeData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ScrapeData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ScrapeData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ScrapeData::MergeFrom(const ScrapeData& from) {
  GOOGLE_CHECK_NE(&from, this);
  meta_.MergeFrom(from.meta_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_quid()) {
      set_quid(from.quid());
    }
    if (from.has_zone()) {
      set_zone(from.zone());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_content()) {
      mutable_content()->::ScrapeData_Data::MergeFrom(from.content());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ScrapeData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScrapeData::CopyFrom(const ScrapeData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScrapeData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000033) != 0x00000033) return false;

  if (has_content()) {
    if (!this->content().IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->meta())) return false;
  return true;
}

void ScrapeData::Swap(ScrapeData* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(id_, other->id_);
    std::swap(quid_, other->quid_);
    std::swap(zone_, other->zone_);
    std::swap(type_, other->type_);
    std::swap(content_, other->content_);
    meta_.Swap(&other->meta_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ScrapeData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ScrapeData_descriptor_;
  metadata.reflection = ScrapeData_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
