#!/bin/bash
LOCDIR="$(pwd)"
LIBMAVPAR="par"
LIBQUID="quid"

if [ -z ${LD_LIBRARY_PATH+x} ]; then
	export LD_LIBRARY_PATH=$LOCDIR/$LIBMAVPAR:$LOCDIR/$LIBQUID
else
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LOCDIR/$LIBMAVPAR:$LOCDIR/$LIBQUID
fi
