<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rule</string>
		<string>rulset</string>
	</array>
	<key>name</key>
	<string>Ruleset</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ruleset</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.ruleset</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rule operators (then)</string>
			<key>match</key>
			<string>\b(then)\b</string>
			<key>name</key>
			<string>keyword.operator.ruleset</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Include</string>
			<key>match</key>
			<string>^\s*\b(include)\b</string>
			<key>name</key>
			<string>keyword.control.include.ruleset</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Commit</string>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.other.ruleset</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.ruleset</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ruleset</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.value.ruleset</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ruleset</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ruleset</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.value.ruleset</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ruleset</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.ruleset</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(unknown)\s+({)</string>
			<key>name</key>
			<string>meta.resource.ruleset</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.ruleset</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ruleset</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.value.ruleset</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ruleset</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.ruleset</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(mime|extension|category|type)\s+("|')([\w-\/\.]+)("|')\s+({)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ruleset</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ruleset</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ruleset</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ruleset</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>\'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ruleset</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ruleset</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruleset</string>
	<key>uuid</key>
	<string>34146e6f-6b26-428b-89d1-2031a1f8dddf</string>
</dict>
</plist>
